# -*- coding: utf8 -*-
# This list of English stop words is taken from the "Glasgow Information
# Retrieval Group". The original list can be found at
# http://ir.dcs.gla.ac.uk/resources/linguistic_utils/stop_words
ENGLISH_STOP_WORDS = frozenset([
    "a", "about", "above", "across", "after", "afterwards", "again", "against",
    "all", "almost", "alone", "along", "already", "also", "although", "always",
    "am", "among", "amongst", "amoungst", "amount", "an", "and", "another",
    "any", "anyhow", "anyone", "anything", "anyway", "anywhere", "are",
    "around", "as", "at", "back", "be", "became", "because", "become",
    "becomes", "becoming", "been", "before", "beforehand", "behind", "being",
    "below", "beside", "besides", "between", "beyond", "bill", "both",
    "bottom", "but", "by", "call", "can", "cannot", "cant", "co", "con",
    "could", "couldnt", "cry", "de", "describe", "detail", "do", "done",
    "down", "due", "during", "each", "eg", "eight", "either", "eleven", "else",
    "elsewhere", "empty", "enough", "etc", "even", "ever", "every", "everyone",
    "everything", "everywhere", "except", "few", "fifteen", "fify", "fill",
    "find", "fire", "first", "five", "for", "former", "formerly", "forty",
    "found", "four", "from", "front", "full", "further", "get", "give", "go",
    "had", "has", "hasnt", "have", "he", "hence", "her", "here", "hereafter",
    "hereby", "herein", "hereupon", "hers", "herself", "him", "himself", "his",
    "how", "however", "hundred", "i", "ie", "if", "in", "inc", "indeed",
    "interest", "into", "is", "it", "its", "itself", "keep", "last", "latter",
    "latterly", "least", "less", "ltd", "made", "many", "may", "me",
    "meanwhile", "might", "mill", "mine", "more", "moreover", "most", "mostly",
    "move", "much", "must", "my", "myself", "name", "namely", "neither",
    "never", "nevertheless", "next", "nine", "no", "nobody", "none", "noone",
    "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on",
    "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our",
    "ours", "ourselves", "out", "over", "own", "part", "per", "perhaps",
    "please", "put", "rather", "re", "same", "see", "seem", "seemed",
    "seeming", "seems", "serious", "several", "she", "should", "show", "side",
    "since", "sincere", "six", "sixty", "so", "some", "somehow", "someone",
    "something", "sometime", "sometimes", "somewhere", "still", "such",
    "system", "take", "ten", "than", "that", "the", "their", "them",
    "themselves", "then", "thence", "there", "thereafter", "thereby",
    "therefore", "therein", "thereupon", "these", "they", "thick", "thin",
    "third", "this", "those", "though", "three", "through", "throughout",
    "thru", "thus", "to", "together", "too", "top", "toward", "towards",
    "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us",
    "very", "via", "was", "we", "well", "were", "what", "whatever", "when",
    "whence", "whenever", "where", "whereafter", "whereas", "whereby",
    "wherein", "whereupon", "wherever", "whether", "which", "while", "whither",
    "who", "whoever", "whole", "whom", "whose", "why", "will", "with",
    "within", "without", "would", "yet", "you", "your", "yours", "yourself",
    "yourselves"])

PERSIAN_STOP_WORDS = frozenset([
    u"درباره", u"زیر", u"بعد", u"دوباره", u"تضاد",
    u"همه", u"تقریبا", u"تنها", u"طول", u"حاضر", u"حال", u"همچنین", u"اگرچه", u"همیشه",
    u"با", u"بین", u"مقدار", u"و", u"دیگر", u"در", u"اگر", u"هیچ", u"هیچکس", u"چیز", u"هرجا",
    u"اطراف", u"از", u"پشت", u"بود", u"زیرا", u"قبل", u"پیش", u"عقب", u"را",
    u"پایین", u"کنار", u"میان", u"هردو", u"اما", u"بوسیله", u"تماس",
    u"توضیح", u"اطلاعات", u"اتمام", u"زمان", u"باهم", u"آن",
    u"دیگر", u"خالی", u"کافی", u"غیره", u"فرد", u"هرکس",
    u"جا", u"بجز", u"کم", u"پر", u"پیدا", u"برای", u"سابق", u"اسبق",
    u"جلو", u"لبریز", u"آینده", u"او", u"اینجا", u"مال", u"من",
    u"چطور", u"چگونه", u"ها", u"اگر", u"علاقه", u"علاقمند", u"است", u"نگه", u"آخر", u"بعدا",
    u"نهایت", u"کمتر", u"ساخت", u"خیلی", u"شاید", u"خلال", u"بیشتر", u"اکثر", u"اکثریت",
    u"حرکت", u"زیاد", u"نام", u"هیچیک", u"هرگز", u"چه", u"بعدی", u"نه",
    u"هیچی", u"حالا", u"هیچجا", u"خاموش", u"اغلب", u"روشن",
    u"روزی", u"تنها", u"فقط", u"یا", u"دیگر", u"دیگران", u"اگرچه", u"ما",
    u"بیرون", u"بالا", u"متعلق", u"جزء", u"لطفا", u"به", u"همان",
    u"همانند", u"نظر", u"جدی", u"چندین", u"نمایش", u"کنار",
    u"خب", u"برخی", u"بعضی", u"بعضیها", u"اوقات", u"زمانها",
    u"جاها", u"همچون", u"سیستم", u"آنها", u"باهم", u"تا",
    u"خوب", u"چه", u"کی", u"هروقت", u"کدام", u"کسی",
    u"برای", u"بدون", u"تو", u"خود", u"راه",
    u"هست", u"هستم", u"هستی", u"هستند", u"هستیم", u"هستید",
    u"نیست", u"نیستم", u"نیستی", u"نیستند", u"نیستیم", u"نیستید",
    u"بود", u"بودم", u"بودیم", u"بودند", u"بودی", u"بودید",
    u"شد", u"شدم", u"شدی", u"شدند", u"شدیم", u"شدید",
    u"نشد", u"نشدم", u"نشدی", u"نشدند", u"نشدیم", u"نشدید",
    u"توانست", u"توانستم", u"توانستی", u"توانستید", u"توانستند", u"توانستیم",
    u"نتوانست", u"نتوانستم", u"نتوانستی", u"نتوانستید", u"نتوانستند", u"نتوانستیم",
    u"یافت", u"یافتم", u"یافتی", u"یافتیم", u"یافتید", u"یافتند",
    u"داد", u"دادم", u"دادی", u"دادیم", u"دادند", u"دادید",
    u"گرفت", u"گرفتم", u"گرفتی", u"گرفتیم", u"گرفتند", u"گرفتید",
    u"رفت", u"رفتم", u"رفتی", u"رفتیم", u"رفتند", u"رفتید",
    u"داشت", u"داشتم", u"داشتی", u"داشتیم", u"داشتند", u"داشتید",
    u"گذاشت", u"گذاشتم", u"گذاشتی", u"گذاشتیم", u"گذاشتند", u"گذاشتید",
    u"دید", u"دیدم", u"دیدی", u"دیدیم", u"دیدید", u"دیدند",
    u"اولین", u"دومین", u"سومین", u"چهارمین", u"پنجمین", u"ششمین", u"هفتمین", u"هشتمین", u"نهمین", u"دهمین",
    u"یک", u"دو", u"سه", u"چهار", u"پنج", u"شش", u"هفت", u"هشت", u"نه", u"ده",
    u"یازده", u"دوازده", u"سیزده", u"چهارده", u"پانزده", u"شانزده", u"هفده",
    u"هجده", u"نوزده", u"بیست", u"سی", u"چهل", u"پنجاه", u"شصت",
    u"هفتاد", u"هشتاد", u"نود", u"صد", u"دویست", u"سیصد", u"چهارصد",
    u"پونصد", u"ششصد", u"هفتصد", u"هشتصد", u"نهصد", u"هزار", u"میلیون", u"میلیارد",
    u"یافت", u"یافتم", u"یافتی", u"یافتیم", u"یافتید", u"یافتند"])
